name: Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build and run tests
        run: gradle clean test aggregate

      - name: Upload Serenity reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Serenity-Reports
          path: target/site/serenity

