name: Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Gradle
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          gradle-version: 8.1

      - name: Install dependencies
        run: gradle clean assemble

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Give execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test aggregate

      - name: Upload Build Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Build-Test-Reports
          path: build/reports/tests/test

      - name: Upload Serenity reports
        uses: actions/upload-artifact@v3
        with:
          name: Serenity-Reports
          path: target/site/serenity

